### ISSUE TITLE
Open contribution policy

### ISSUE THREAD

**Issue by namyeop** [finecodekr/hometaxbot#1]
안녕하세요! 좋은 소스 공유해주셔서 감사합니다.

현재 공동인증서만 사용하고 있는 것으로 확인되는데요.
혹시 간편인증서 모듈도 개발이 되어 있는지, 혹시 가능하다면 간편인증 모듈 개발 기여가 가능할지 문의드립니다.

**Comment by youngrok** [comment]
개발 기여에 대해서는 열려 있습니다. 곧 CONTRIBUTING 문서를 작성해서 올려둘 텐데, 문서가 나오기 전이라도 Pull Request 보내주시면 검토해보겠습니다.

그런데, 간편인증은 대부분 사람이 개입해서 인증하도록 해서 자동화가 어렵지 않나요? 인증한 다음 그 쿠키를 받아오면 [login_with_cookie](https://github.com/finecodekr/hometaxbot/blob/dc0c1472fa13dabfb98b5ca6abdb5880f8fa1498/hometaxbot/scraper/__init__.py#L196) 이용해서 스크래핑을 돌릴 수 있긴 합니다만.

**Comment by namyeop** [comment]
맞습니다. 인증은 세션 단위로 유지되며, 매 세션마다 사용자가 인증을 해주어야 합니다.

다만 인증의 용이성 때문에 점점 공동인증서보다 간편 인증서 사용 비율이 높아지고 있어서 관련 기능도 있으면 좋을 것 같아 제안드렸습니다.

코드를 다 들여다보지는 않았으나, [login_with_cookie](https://github.com/finecodekr/hometaxbot/blob/dc0c1472fa13dabfb98b5ca6abdb5880f8fa1498/hometaxbot/scraper/__init__.py#L196)에 활용할 수 있는 값이 간편인증에도 있으려나 모르겠네요. 한 번 찾아보겠습니다 🫤

**Comment by youngrok** [comment]
https://github.com/finecodekr/hometaxbot/blob/main/CONTRIBUTING.md 기여 방법에 대한 문서를 추가했습니다.
